set -g mouse on
setw -g mode-keys vi
set-option -g set-clipboard on
set -g status-right ""

set -g allow-rename off
set -g automatic-rename off

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
#set -g @plugin 'catppuccin/tmux'
set -g @plugin 'wfxr/tmux-power'

# Theme settings
#set -g @catppuccin_flavor 'mocha'
set -g @tmux_power_theme 'everforest'

# Status bar position
set -g status-justify left

set -g allow-rename off
set -g automatic-rename off

# Keep this at the very bottom
run '~/.tmux/plugins/tpm/tpm'
set -s set-clipboard on
